[package]
name = "p1-exporter"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3", features = ["derive"]}
dsmr5 = "0.2"
prometheus-client = "0.21"
tiny_http = "0.12"
